services:
  sandbox:
    build: .
    volumes:
      - type: bind
        source: ./shared-register
        target: /shared-register
      - type: bind
        source: ./vol
        target: /work
    # コンテナを起動させ続ける
    # https://qiita.com/messhii222/items/01ae86ebedd576355fab
    tty: true
    stdin_open: true

